---
platform: linux

image_resource:
  type: docker-image
  source: {repository: idahobean/dcind-golang-npm}

inputs:
- name: sinopia2
- name: npm-resource
  path: gopath/src/github.com/idahobean/npm-resource
- name: sample-node
  path: gopath/src/github.com/idahobean/npm-resource/sample-node

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/idahobean/npm-resource/scripts/ci
