---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: npm-resource
  path: gopath/src/github.com/idahobean/npm-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/idahobean/npm-resource/scripts/ci
